apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: backbase-api-ingress
  namespace: backbase-staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: backend.staging.backbase.co
    http:
      paths:
      - path: /
        backend:
          serviceName: backbase-api-service
          servicePort: 80