apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dashboard-api-ingress
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: backend.staging.hookman.ng
    http:
      paths:
      - path: /
        backend:
          serviceName: hookman-dashboard-api-service
          servicePort: 80