apiVersion: apps/v1
kind: Deployment
metadata:
  name: backbase-dashboard-api
  namespace: backbase-production
  labels:
    app: backend
    type: api
    project: backbase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      type: api
      project: backbase
  template:
    metadata:
      labels:
        app: backend
        type: api
        project: backbase
    spec:
      containers:
      - name: backbase-dashboard-api-container
        image: registry.digitalocean.com/hookman-registry/backbase-dashboard-api
        env:
        - name: NODE_ENV
          value: "production"
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: hookman-secret
              key: postgres.host
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: registry-hookman-registry
---
apiVersion: v1
kind: Service
metadata:
  name: backbase-api-service
spec:
  selector:
    app: backend
    type: api
    project: backbase
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000