apiVersion: apps/v1
kind: Deployment
metadata:
  name: backbase-dashboard-api
  namespace: backbase-staging
  labels:
    app: backend
    type: api
    project: backbase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      type: api
      project: backbase
  template:
    metadata:
      labels:
        app: backend
        type: api
        project: backbase
    spec:
      containers:
      - name: backbase-dashboard-api-container
        image: registry.digitalocean.com/hookman-registry/backbase-dashboard-api
        env:
        - name: NODE_ENV
          value: "staging"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: backbase-secret
              key: redis.host
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backbase-secret
              key: redis.password
        - name: AMQP_URL
          valueFrom:
            secretKeyRef:
              name: backbase-secret
              key: rabbitmq.host
        - name: AMQP_USER
          valueFrom:
            secretKeyRef:
              name: backbase-secret
              key: rabbitmq.username
        - name: AMQP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backbase-secret
              key: rabbitmq.password
        - name: MONGODB_HOST
          valueFrom:
            secretKeyRef:
              name: backbase-secret
              key: mongodb.url
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: backbase-secret
              key: mongodb.username
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backbase-secret
              key: mongodb.password
        - name: MONGODB_PORT
          valueFrom:
            secretKeyRef:
              name: backbase-secret
              key: mongodb.port
        - name: MONGODB_DB
          value: "BACKBASE_DB_STAGING"
        

        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: backbase-secret
              key: cloudinary.cloud_name
        - name: CLOUDINARY_API_KEY
          valueFrom:
            secretKeyRef:
              name: backbase-secret
              key: cloudinary.api_key
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: backbase-secret
              key: cloudinary.api_secret
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backbase-secret
              key: stripe.secret_key
        - name: STRIPE_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: backbase-secret
              key: stripe.public_key
        - name: PAYSTACK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backbase-secret
              key: paystack.secret_key
        - name: PAYSTACK_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: backbase-secret
              key: paystack.public_key
        - name: PLAID_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: backbase-secret
              key: plaid.client_id
        - name: PLAID_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: backbase-secret
              key: plaid.public_key
        - name: PLAID_SECRET
          valueFrom:
            secretKeyRef:
              name: backbase-secret
              key: plaid.secret
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: backbase-secret
              key: sentry.dsn
        - name: EMAIL_SERVICE
          valueFrom:
            secretKeyRef:
              name: backbase-secret
              key: email.service
        - name: BILLING_SERVICE
          valueFrom:
            secretKeyRef:
              name: backbase-secret
              key: billing.service
        - name: EVENTS_SERVICE
          valueFrom:
            secretKeyRef:
              name: backbase-secret
              key: events.service
        - name: JOB_SCHEDULER_SERVICE
          valueFrom:
            secretKeyRef:
              name: backbase-secret
              key: job_scheduler.service
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: registry-hookman-registry
---
apiVersion: v1
kind: Service
metadata:
  name: backbase-api-service
spec:
  selector:
    app: backend
    type: api
    project: backbase
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000